-- =============================================================================
-- Daily Warmup - Supabase schema
-- Run this once in your Supabase project: SQL Editor -> New query -> Run.
-- After this, the app auto-seeds 100 sample questions on first visit and picks
-- today's question automatically. No cron needed.
-- =============================================================================

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  prompt text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_questions (
  selected_on date primary key,
  question_id bigint not null references public.questions(id),
  created_at timestamptz not null default now()
);

create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id),
  answer text not null,
  display_name text not null default 'Anonymous',
  created_at timestamptz not null default now()
);

create index if not exists answers_created_at_idx on public.answers (created_at desc);

-- Enable Row Level Security. All app access goes through the server using the
-- SECRET key (which bypasses RLS), so no public policies are needed. This is
-- the most secure setup: the browser can never read/write Supabase directly.
alter table public.questions enable row level security;
alter table public.daily_questions enable row level security;
alter table public.answers enable row level security;

-- OPTIONAL: to use YOUR OWN questions instead of the app's 100 samples, insert
-- them here BEFORE the first visit (auto-seed only runs when the table is empty):
-- insert into public.questions (prompt) values
--   ('What is your favorite book?'),
--   ('What is one goal for this week?');
